### ISSUE TITLE
fsp files

### ISSUE THREAD

**Issue by avpanov** [Hinamoooon/MENP#1]
Thank you for this package. I have no Lumerical and I cannot understand the content of *.fsp files. Can you convert their to a human readable form? Or describe their in detail?
Thus it can be utilized with another FDTD solvers.

**Comment by Hinamoooon** [comment]
Hi @avpanov,

Thank you for the inquiry.
The fsp files are Lumerical Project that contains simulation settings/configurations and results. They are binary and not a human-readable form.
The fsp file is used to simulate the electromagnetic responses of nanostructures. As meaningful data has already been exported to "ENxyzf.mat", which can be read using MATLAB, you would not need to see details of the fsp files.

If you want to use the other FDTD solvers, what you need is refractive index and electric fields at each grid point of Yee meshes. See "ENxyzf.mat" to understand the required file structure. Please feel free to ask for assistance if you need it.
